### ISSUE TITLE
[Feature Request] Vereinfachtes setzen der Einschaltdauer

### ISSUE THREAD

**Issue by Hypnos3** [hobbyquaker/ccu-addon-node-red#12]
Hallo,

vielleicht wäre eine Einstellung möglich, das man eine Einschaltdauer mit geben kann.

Wenn ich das richtig verstehe muss ich dafür die "ON_TIME" setzen und danach einschalten "STATE" auf true.

In der Form funktioniert es leider nicht:
![image](https://user-images.githubusercontent.com/12692680/40654814-a518c324-633f-11e8-8ec9-26b1d2789828.png)

Da ich sicherstellen muss, das es in der richtigen Reihenfolge erfolgt, wird es dann irgendwie "sperrig":
![image](https://user-images.githubusercontent.com/12692680/40654571-f6c6b402-633e-11e8-9765-3481f992c9c8.png)

Vielleicht kann man eine Möglichkeit schaffen das einfacher zu realisieren?
Vielleicht mit einer extra Node, wo man einen datenpunkt wie "ON_TIME" auf einen beliebigen festen Wert oder eine Eigenschaft aus dem MSG objekt setzen kann:
![image](https://user-images.githubusercontent.com/12692680/40659162-b93a5788-634d-11e8-816c-8b37ba320b9d.png)
und was danach das msg objekt einfach weitergibt.

**Comment by hobbyquaker** [comment]
Steckt nun in v0.0.26. Hab allerdings kein neuen Node geschaffen, stattdessen bietet der Value Node jetzt Eingabefelder für ON_TIME und RAMP_TIME an (falls vom Kanal unterstützt).

**Comment by Hypnos3** [comment]
Danke funktioniert!
