### ISSUE TITLE
Node for Google Assistent integration ?

### ISSUE THREAD

**Issue by drose28357** [hobbyquaker/ccu-addon-node-red#2]
Feature-Request. Even to an unstable Version ;-)
I dont understand this Node thing. But i am looking or a standardizeable Google Asistent integration with Homematic. Mayby Node could do the trick.

But we need a Integration-Node.
Somethink like this ...
https://www.npmjs.com/package/google-assistant-node 
and this
https://www.jovo.tech/blog/google-action-tutorial-nodejs/ 
or this
https://github.com/actions-on-google/smart-home-nodejs

**Comment by hobbyquaker** [comment]
This Addon only delivers the basic Node-RED installation and some Nodes for the CCU connection. I consider Google Assistant Integration as "out of scope" for this project.
But if you search for "Google" here: https://flows.nodered.org/ you will see that there are already some Nodes available that integrate Google Assistant. I have zero knowledge of that google stuff, but I think it it is already possible to integrate that with Node-RED.
