### ISSUE TITLE
Keine Auswahlliste der Kanäle/Datenpunkte bei CUxD devices

### ISSUE THREAD

**Issue by Hypnos3** [hobbyquaker/ccu-addon-node-red#5]
Bei CUxD gibt es keine Auswahl der verfügbaren Chanels:
![image](https://user-images.githubusercontent.com/12692680/39654091-d9b9c09c-4ff3-11e8-9b76-5385c03780ec.png)

Bei den anderen Typen ist das vorhanden:
![image](https://user-images.githubusercontent.com/12692680/39654112-e801afb6-4ff3-11e8-8f99-1936a03a1614.png)

**Comment by hobbyquaker** [comment]
sollte in v0.0.16 gefixt sein.

**Comment by Hypnos3** [comment]
Danke, funktioniert jetzt!
